### PR TITLE
quality of life improvements

### PR DESCRIPTION
**Pull request by jesdynf**
Was working with GCM project, and found both of these generally useful.

### CODE REVIEW

**Comment by jesdynf** [comment]
(I did sign the CLA, user jesdynf).

**Comment by kroikie** [comment]
Thanks for your PR, please be sure to sign the CLA.

**Comment by jesdynf** [comment]
Done before signing, the commits were just under the wrong email address
(you want jesdynf@gmail.com).

On Saturday, September 26, 2015, Arthur Thompson <notifications@github.com>
wrote:

> Thanks for your PR, please be sure to sign the CLA.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/googlesamples/google-services/pull/74#issuecomment-143516775>
> .
>


-- 
Asher Densmore-Lynn <jesdynf@gmail.com>

**Comment by silvolu** [comment]
@jesdynf the problem is that it appears that you have signed the Android cla instead of the Google cla, and we need you to sign the latter for this repo. Please sign it again making sure that in the cla form under **You plan to submit contributions to** you select **Any other Google project**.

**Comment by jesdynf** [comment]
Whoops, done.

On Mon, Sep 28, 2015 at 11:45 AM, Silvano Luciani <notifications@github.com>
wrote:

> @jesdynf <https://github.com/jesdynf> the problem is that it appears that
> you have signed the Android cla instead of the Google cla, and we need you
> to sign the latter for this repo. Please sign it again making sure that in
> the cla form under *You plan to submit contributions to* you select *Any
> other Google project*.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/googlesamples/google-services/pull/74#issuecomment-143800604>
> .
>



-- 
Asher Densmore-Lynn <jesdynf@gmail.com>

**Comment by jesdynf** [comment]
That person (asher@mycomicshop.com) is me, I've just got the wrong address
on those commits.

On Mon, Sep 28, 2015 at 12:42 PM, googlebot <notifications@github.com>
wrote:

> We found a Contributor License Agreement for you (the sender of this pull
> request), but were unable to find agreements for the commit author(s). If
> you authored these, maybe you used a different email address in the git
> commits than was used to sign the CLA (login here
> <https://cla.developers.google.com/> to double check)? If these were
> authored by someone else, then they will need to sign a CLA as well, and
> confirm that they're okay with these being contributed to Google.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/googlesamples/google-services/pull/74#issuecomment-143816832>
> .
>



-- 
Asher Densmore-Lynn <jesdynf@gmail.com>

**Comment by silvolu** [comment]
CLA is good.

**Pull request closed without merging**
